const translations = {
  en: {
    legalDisclaimer: "Legal Disclaimer",
    reviewAcceptDisclaimer: "Review and accept the disclaimer to proceed",
    startBuildingSwms: "Start Building SWMS",
    createComprehensiveDocumentation: "Create comprehensive safety documentation",
    "nav.dashboard": "Dashboard",
    "nav.swms-builder": "SWMS Builder", 
    "nav.my-swms": "My SWMS",
    "nav.safety-library": "Safety Library",
    "nav.help": "Help & Support",
    "nav.settings": "Settings",
    "btn.new-swms": "New SWMS",
    "btn.view-all": "View All",
    "btn.generate": "Generate",
    "swms.step1.title": "Project & Contractor Details",
    "swms.step1.desc": "Project information, contractor details, and high-risk work identification",
    "swms.step2.title": "Work Activities & Risk Assessment", 
    "swms.step2.desc": "Detailed work breakdown and comprehensive risk assessments",
    "swms.step3.title": "Plant, Equipment & Training",
    "swms.step3.desc": "Equipment specifications, training requirements, and permits",
    "swms.step4.title": "Emergency & Monitoring",
    "swms.step4.desc": "Emergency procedures and review/monitoring processes",
    "swms.step5.title": "Legal Disclaimer",
    "swms.step5.desc": "Accept terms and liability disclaimer",
    "swms.step6.title": "Final Document",
    "swms.step6.desc": "Generate complete SWMS document",
    "swms.back.dashboard": "Back to Dashboard",
    "swms.builder": "SWMS Builder",
    "swms.create.comprehensive": "Create comprehensive safety documentation",
    "swms.save.close": "Save & Close",
    "swms.step": "Step",
    "swms.of": "of",
    "swms.progress": "Progress", 
    "swms.complete": "Complete",
    "swms.title": "SWMS Title",
    "swms.trade.type": "Trade Type",
    "swms.select.trade": "Select your trade",
    "swms.job.name": "Job Name",
    "swms.job.number": "Job Number",
    "swms.project.address": "Project Address",
    "swms.project.location": "Project Location/Description",
    // Dashboard translations
    "manageSafetyCompliance": "Manage Safety Compliance",
    "draftSwms": "Draft SWMS",
    "saveCompleteLater": "Save & Complete Later",
    "completedSwms": "Completed SWMS",
    "projectSpecificDocumentation": "Project-Specific Documentation",
    "createNewSwms": "Create New SWMS",
    "quickStart": "Quick Start",
    "recentSwmsDocuments": "Recent SWMS Documents",
    "viewAll": "View All",
    "quickActions": "Quick Actions",
    "nav.ai-generator": "AI Generator",

    "nav.team": "Team",
    "nav.analytics": "Analytics",
    "nav.account": "Account",
    // Missing translation keys
    "projectDetails": "Project Details",
    "projectDetailsDesc": "Enter comprehensive project information and contractor details",
    "tradeSelection": "Trade Selection", 
    "selectTrade": "Select your trade type",
    "activities": "Activities",
    "activitySelection": "Activity Selection",
    "searchActivities": "Search activities...",
    "selected": "selected",
    "selectAll": "Select All",
    "deselectAll": "Deselect All",
    // Placeholder texts
    "placeholder.selectTrade": "Select your trade",
    "placeholder.jobName": "e.g., Office Tower Construction",
    "placeholder.jobNumber": "e.g., JOB-2025-001",
    "placeholder.projectAddress": "Enter the complete project address",
    "placeholder.projectLocation": "e.g., Level 5 Office Fitout, Main Building",
    "placeholder.swmsTitle": "e.g., Electrical Installation - Office Fitout"
  },
  zh: {
    legalDisclaimer: "法律免责声明",
    reviewAcceptDisclaimer: "查看并接受免责声明以继续",
    startBuildingSwms: "开始构建SWMS",
    createComprehensiveDocumentation: "创建综合安全文档",
    "nav.dashboard": "仪表板",
    "nav.swms-builder": "SWMS构建器",
    "nav.my-swms": "我的SWMS",
    "nav.safety-library": "安全库", 
    "nav.help": "帮助和支持",
    "nav.settings": "设置",
    "btn.new-swms": "新建SWMS",
    "btn.view-all": "查看全部",
    "btn.generate": "生成",
    "swms.step1.title": "项目和承包商详情",
    "swms.step1.desc": "项目信息、承包商详情和高风险工作识别",
    "swms.step2.title": "工作活动和风险评估",
    "swms.step2.desc": "详细工作分解和综合风险评估",
    "swms.step3.title": "设备、器材和培训",
    "swms.step3.desc": "设备规格、培训要求和许可证",
    "swms.step4.title": "紧急情况和监控",
    "swms.step4.desc": "紧急程序和审查/监控流程",
    "swms.step5.title": "法律免责声明",
    "swms.step5.desc": "接受条款和责任免责声明",
    "swms.step6.title": "最终文档",
    "swms.step6.desc": "生成完整的SWMS文档",
    "swms.back.dashboard": "返回仪表板",
    "swms.builder": "SWMS构建器",
    "swms.create.comprehensive": "创建综合安全文档",
    "swms.save.close": "保存并关闭",
    "swms.step": "步骤",
    "swms.of": "共",
    "swms.progress": "进度",
    "swms.complete": "完成",
    "swms.title": "SWMS标题",
    "swms.trade.type": "行业类型",
    "swms.select.trade": "选择您的行业",
    "swms.job.name": "工作名称",
    "swms.job.number": "工作编号",
    "swms.project.address": "项目地址",
    "swms.project.location": "项目位置/描述",
    // Dashboard translations
    "manageSafetyCompliance": "管理安全合规性",
    "draftSwms": "草稿SWMS",
    "saveCompleteLater": "保存并稍后完成",
    "completedSwms": "已完成的SWMS",
    "projectSpecificDocumentation": "项目特定文档",
    "createNewSwms": "创建新SWMS",
    "quickStart": "快速开始",
    "recentSwmsDocuments": "最近的SWMS文档",
    "viewAll": "查看全部",
    "quickActions": "快速操作",
    "nav.ai-generator": "AI生成器",
    "nav.team": "团队",
    "nav.analytics": "分析",
    "nav.account": "账户",
    // Missing translation keys for Chinese
    "projectDetails": "项目详情",
    "projectDetailsDesc": "输入全面的项目信息和承包商详情",
    "tradeSelection": "行业选择",
    "selectTrade": "选择您的行业类型",
    "activities": "活动",
    "activitySelection": "活动选择",
    "searchActivities": "搜索活动...",
    "selected": "已选择",
    // Placeholder texts
    "placeholder.selectTrade": "选择您的工种",
    "placeholder.jobName": "例如：办公大楼建设",
    "placeholder.jobNumber": "例如：JOB-2025-001",
    "placeholder.projectAddress": "输入完整的项目地址",
    "placeholder.projectLocation": "例如：5楼办公室装修，主楼",
    "placeholder.swmsTitle": "例如：电气安装 - 办公室装修"
  },
  es: {
    legalDisclaimer: "Descargo Legal",
    reviewAcceptDisclaimer: "Revise y acepte el descargo de responsabilidad para continuar",
    startBuildingSwms: "Comenzar a Construir SWMS",
    createComprehensiveDocumentation: "Crear documentación integral de seguridad",
    "nav.dashboard": "Panel",
    "nav.swms-builder": "Constructor SWMS",
    "nav.my-swms": "Mis SWMS",
    "nav.safety-library": "Biblioteca de Seguridad",
    "nav.help": "Ayuda y Soporte",
    "nav.settings": "Configuración",
    "btn.new-swms": "Nuevo SWMS",
    "btn.view-all": "Ver Todo",
    "btn.generate": "Generar",
    "swms.step1.title": "Detalles del Proyecto y Contratista",
    "swms.step1.desc": "Información del proyecto, detalles del contratista e identificación de trabajo de alto riesgo",
    "swms.step2.title": "Actividades de Trabajo y Evaluación de Riesgos",
    "swms.step2.desc": "Desglose detallado del trabajo y evaluaciones integrales de riesgos",
    "swms.step3.title": "Planta, Equipo y Entrenamiento",
    "swms.step3.desc": "Especificaciones de equipo, requisitos de entrenamiento y permisos",
    "swms.step4.title": "Emergencia y Monitoreo",
    "swms.step4.desc": "Procedimientos de emergencia y procesos de revisión/monitoreo",
    "swms.step5.title": "Descargo Legal",
    "swms.step5.desc": "Aceptar términos y descargo de responsabilidad",
    "swms.step6.title": "Documento Final",
    "swms.step6.desc": "Generar documento SWMS completo",
    "swms.back.dashboard": "Volver al Panel",
    "swms.builder": "Constructor SWMS",
    "swms.create.comprehensive": "Crear documentación integral de seguridad",
    "swms.save.close": "Guardar y Cerrar",
    "swms.step": "Paso",
    "swms.of": "de",
    "swms.progress": "Progreso",
    "swms.complete": "Completo",
    "swms.title": "Título SWMS",
    "swms.trade.type": "Tipo de Oficio",
    "swms.select.trade": "Seleccione su oficio",
    "swms.job.name": "Nombre del Trabajo",
    "swms.job.number": "Número de Trabajo",
    "swms.project.address": "Dirección del Proyecto",
    "swms.project.location": "Ubicación/Descripción del Proyecto",
    // Dashboard translations
    "manageSafetyCompliance": "Gestionar Cumplimiento de Seguridad",
    "draftSwms": "Borrador SWMS",
    "saveCompleteLater": "Guardar y Completar Más Tarde",
    "completedSwms": "SWMS Completados",
    "projectSpecificDocumentation": "Documentación Específica del Proyecto",
    "createNewSwms": "Crear Nuevo SWMS",
    "quickStart": "Inicio Rápido",
    "recentSwmsDocuments": "Documentos SWMS Recientes",
    "viewAll": "Ver Todo",
    "quickActions": "Acciones Rápidas",
    "nav.ai-generator": "Generador IA",
    "nav.team": "Equipo",
    "nav.analytics": "Análisis",
    "nav.account": "Cuenta"
  },
  fr: {
    legalDisclaimer: "Avertissement Légal",
    reviewAcceptDisclaimer: "Examinez et acceptez l'avertissement pour continuer",
    startBuildingSwms: "Commencer à Construire SWMS",
    createComprehensiveDocumentation: "Créer une documentation de sécurité complète",
    "nav.dashboard": "Tableau de Bord",
    "nav.swms-builder": "Constructeur SWMS",
    "nav.my-swms": "Mes SWMS",
    "nav.safety-library": "Bibliothèque de Sécurité",
    "nav.help": "Aide et Support",
    "nav.settings": "Paramètres",
    "btn.new-swms": "Nouveau SWMS",
    "btn.view-all": "Voir Tout",
    "btn.generate": "Générer",
    "swms.step1.title": "Détails du Projet et Entrepreneur",
    "swms.step1.desc": "Informations du projet, détails de l'entrepreneur et identification des travaux à haut risque",
    "swms.step2.title": "Activités de Travail et Évaluation des Risques",
    "swms.step2.desc": "Répartition détaillée du travail et évaluations complètes des risques",
    "swms.step3.title": "Équipement, Matériel et Formation",
    "swms.step3.desc": "Spécifications d'équipement, exigences de formation et permis",
    "swms.step4.title": "Urgence et Surveillance",
    "swms.step4.desc": "Procédures d'urgence et processus d'examen/surveillance",
    "swms.step5.title": "Avertissement Légal",
    "swms.step5.desc": "Accepter les termes et l'avertissement de responsabilité",
    "swms.step6.title": "Document Final",
    "swms.step6.desc": "Générer le document SWMS complet",
    "swms.back.dashboard": "Retour au Tableau de Bord",
    "swms.builder": "Constructeur SWMS",
    "swms.create.comprehensive": "Créer une documentation de sécurité complète",
    "swms.save.close": "Enregistrer et Fermer",
    "swms.step": "Étape",
    "swms.of": "de",
    "swms.progress": "Progrès",
    "swms.complete": "Terminé",
    "swms.title": "Titre SWMS",
    "swms.trade.type": "Type de Métier",
    "swms.select.trade": "Sélectionnez votre métier",
    "swms.job.name": "Nom du Travail",
    "swms.job.number": "Numéro de Travail",
    "swms.project.address": "Adresse du Projet",
    "swms.project.location": "Emplacement/Description du Projet",
    // Dashboard translations
    "manageSafetyCompliance": "Gérer la Conformité de Sécurité",
    "draftSwms": "Brouillon SWMS",
    "saveCompleteLater": "Enregistrer et Terminer Plus Tard",
    "completedSwms": "SWMS Terminés",
    "projectSpecificDocumentation": "Documentation Spécifique au Projet",
    "createNewSwms": "Créer Nouveau SWMS",
    "quickStart": "Démarrage Rapide",
    "recentSwmsDocuments": "Documents SWMS Récents",
    "viewAll": "Voir Tout",
    "quickActions": "Actions Rapides",
    "nav.ai-generator": "Générateur IA",
    "nav.team": "Équipe",
    "nav.analytics": "Analytique",
    "nav.account": "Compte"
  },
  de: {
    legalDisclaimer: "Rechtlicher Haftungsausschluss",
    reviewAcceptDisclaimer: "Überprüfen und akzeptieren Sie den Haftungsausschluss, um fortzufahren",
    startBuildingSwms: "SWMS-Erstellung Beginnen",
    createComprehensiveDocumentation: "Umfassende Sicherheitsdokumentation erstellen",
    "nav.dashboard": "Dashboard",
    "nav.swms-builder": "SWMS-Builder",
    "nav.my-swms": "Meine SWMS",
    "nav.safety-library": "Sicherheitsbibliothek",
    "nav.help": "Hilfe & Support",
    "nav.settings": "Einstellungen",
    "btn.new-swms": "Neue SWMS",
    "btn.view-all": "Alle Anzeigen",
    "btn.generate": "Generieren",
    "swms.step1.title": "Projekt- und Auftragnehmerdetails",
    "swms.step1.desc": "Projektinformationen, Auftragnehmerdetails und Hochrisiko-Arbeitsidentifikation",
    "swms.step2.title": "Arbeitsaktivitäten und Risikobewertung",
    "swms.step2.desc": "Detaillierte Arbeitsaufteilung und umfassende Risikobewertungen",
    "swms.step3.title": "Anlagen, Ausrüstung und Schulung",
    "swms.step3.desc": "Ausrüstungsspezifikationen, Schulungsanforderungen und Genehmigungen",
    "swms.step4.title": "Notfall und Überwachung",
    "swms.step4.desc": "Notfallverfahren und Überprüfungs-/Überwachungsprozesse",
    "swms.step5.title": "Rechtlicher Haftungsausschluss",
    "swms.step5.desc": "Bedingungen und Haftungsausschluss akzeptieren",
    "swms.step6.title": "Abschlussdokument",
    "swms.step6.desc": "Vollständiges SWMS-Dokument generieren",
    "swms.back.dashboard": "Zurück zum Dashboard",
    "swms.builder": "SWMS-Builder",
    "swms.create.comprehensive": "Umfassende Sicherheitsdokumentation erstellen",
    "swms.save.close": "Speichern & Schließen",
    "swms.step": "Schritt",
    "swms.of": "von",
    "swms.progress": "Fortschritt",
    "swms.complete": "Abgeschlossen",
    "swms.title": "SWMS-Titel",
    "swms.trade.type": "Gewerbetyp",
    "swms.select.trade": "Wählen Sie Ihr Gewerbe",
    "swms.job.name": "Arbeitsname",
    "swms.job.number": "Arbeitsnummer",
    "swms.project.address": "Projektadresse",
    "swms.project.location": "Projektstandort/Beschreibung",
    // Dashboard translations
    "manageSafetyCompliance": "Sicherheitskonformität Verwalten",
    "draftSwms": "Entwurf SWMS",
    "saveCompleteLater": "Speichern und Später Vervollständigen",
    "completedSwms": "Abgeschlossene SWMS",
    "projectSpecificDocumentation": "Projektspezifische Dokumentation",
    "createNewSwms": "Neue SWMS Erstellen",
    "quickStart": "Schnellstart",
    "recentSwmsDocuments": "Kürzliche SWMS-Dokumente",
    "viewAll": "Alle Anzeigen",
    "quickActions": "Schnelle Aktionen",
    "nav.ai-generator": "KI-Generator",
    "nav.team": "Team",
    "nav.analytics": "Analytik",
    "nav.account": "Konto"
  },
  ja: {
    legalDisclaimer: "法的免責事項",
    reviewAcceptDisclaimer: "免責事項を確認し、同意して続行してください",
    startBuildingSwms: "SWMS構築を開始",
    createComprehensiveDocumentation: "包括的な安全文書を作成",
    "nav.dashboard": "ダッシュボード",
    "nav.swms-builder": "SWMSビルダー",
    "nav.my-swms": "マイSWMS",
    "nav.safety-library": "安全ライブラリ",
    "nav.help": "ヘルプ＆サポート",
    "nav.settings": "設定",
    "btn.new-swms": "新しいSWMS",
    "btn.view-all": "すべて表示",
    "btn.generate": "生成",
    "swms.step1.title": "プロジェクトと請負業者の詳細",
    "swms.step1.desc": "プロジェクト情報、請負業者の詳細、高リスク作業の特定",
    "swms.step2.title": "作業活動とリスク評価",
    "swms.step2.desc": "詳細な作業分解と包括的なリスク評価",
    "swms.step3.title": "プラント、設備、訓練",
    "swms.step3.desc": "設備仕様、訓練要件、許可証",
    "swms.step4.title": "緊急時と監視",
    "swms.step4.desc": "緊急手順とレビュー/監視プロセス",
    "swms.step5.title": "法的免責事項",
    "swms.step5.desc": "条項と責任免責に同意",
    "swms.step6.title": "最終文書",
    "swms.step6.desc": "完全なSWMS文書を生成",
    "swms.back.dashboard": "ダッシュボードに戻る",
    "swms.builder": "SWMSビルダー",
    "swms.create.comprehensive": "包括的な安全文書を作成",
    "swms.save.close": "保存して閉じる",
    "swms.step": "ステップ",
    "swms.of": "の",
    "swms.progress": "進捗",
    "swms.complete": "完了",
    "swms.title": "SWMSタイトル",
    "swms.trade.type": "職種タイプ",
    "swms.select.trade": "職種を選択",
    "swms.job.name": "作業名",
    "swms.job.number": "作業番号",
    "swms.project.address": "プロジェクト住所",
    "swms.project.location": "プロジェクト場所/説明",
    // Dashboard translations
    "manageSafetyCompliance": "安全コンプライアンス管理",
    "draftSwms": "下書きSWMS",
    "saveCompleteLater": "保存して後で完成",
    "completedSwms": "完成したSWMS",
    "projectSpecificDocumentation": "プロジェクト固有のドキュメント",
    "createNewSwms": "新しいSWMSを作成",
    "quickStart": "クイックスタート",
    "recentSwmsDocuments": "最近のSWMS文書",
    "viewAll": "すべて表示",
    "quickActions": "クイックアクション",
    "nav.ai-generator": "AIジェネレーター",
    "nav.team": "チーム",
    "nav.analytics": "分析",
    "nav.account": "アカウント"
  },
  ko: {
    legalDisclaimer: "법적 면책조항",
    reviewAcceptDisclaimer: "면책조항을 검토하고 동의하여 진행하세요",
    startBuildingSwms: "SWMS 구축 시작",
    createComprehensiveDocumentation: "포괄적인 안전 문서 작성",
    "nav.dashboard": "대시보드",
    "nav.swms-builder": "SWMS 빌더",
    "nav.my-swms": "내 SWMS",
    "nav.safety-library": "안전 라이브러리",
    "nav.help": "도움말 및 지원",
    "nav.settings": "설정",
    "btn.new-swms": "새 SWMS",
    "btn.view-all": "모두 보기",
    "btn.generate": "생성",
    "swms.step1.title": "프로젝트 및 계약자 세부사항",
    "swms.step1.desc": "프로젝트 정보, 계약자 세부사항 및 고위험 작업 식별",
    "swms.step2.title": "작업 활동 및 위험 평가",
    "swms.step2.desc": "세부 작업 분해 및 포괄적인 위험 평가",
    "swms.step3.title": "설비, 장비 및 교육",
    "swms.step3.desc": "장비 사양, 교육 요구사항 및 허가증",
    "swms.step4.title": "응급상황 및 모니터링",
    "swms.step4.desc": "응급 절차 및 검토/모니터링 프로세스",
    "swms.step5.title": "법적 면책조항",
    "swms.step5.desc": "조건 및 책임 면책 동의",
    "swms.step6.title": "최종 문서",
    "swms.step6.desc": "완전한 SWMS 문서 생성",
    "swms.back.dashboard": "대시보드로 돌아가기",
    "swms.builder": "SWMS 빌더",
    "swms.create.comprehensive": "포괄적인 안전 문서 작성",
    "swms.save.close": "저장 후 닫기",
    "swms.step": "단계",
    "swms.of": "중",
    "swms.progress": "진행률",
    "swms.complete": "완료",
    "swms.title": "SWMS 제목",
    "swms.trade.type": "업종 유형",
    "swms.select.trade": "업종을 선택하세요",
    "swms.job.name": "작업명",
    "swms.job.number": "작업번호",
    "swms.project.address": "프로젝트 주소",
    "swms.project.location": "프로젝트 위치/설명",
    // Dashboard translations
    "manageSafetyCompliance": "안전 준수 관리",
    "draftSwms": "초안 SWMS",
    "saveCompleteLater": "저장하고 나중에 완료",
    "completedSwms": "완료된 SWMS",
    "projectSpecificDocumentation": "프로젝트별 문서",
    "createNewSwms": "새 SWMS 생성",
    "quickStart": "빠른 시작",
    "recentSwmsDocuments": "최근 SWMS 문서",
    "viewAll": "모두 보기",
    "quickActions": "빠른 작업",
    "nav.ai-generator": "AI 생성기",
    "nav.team": "팀",
    "nav.analytics": "분석",
    "nav.account": "계정",
    // Placeholder texts
    "placeholder.selectTrade": "직종을 선택하세요",
    "placeholder.jobName": "예: 오피스 타워 건설",
    "placeholder.jobNumber": "예: JOB-2025-001 (선택사항)",
    "placeholder.projectAddress": "완전한 프로젝트 주소를 입력하세요",
    "placeholder.projectLocation": "예: 5층 오피스 피트아웃, 본관",
    "placeholder.swmsTitle": "예: 전기 설치 - 오피스 피트아웃"
  },
  ar: {
    legalDisclaimer: "إخلاء المسؤولية القانونية",
    reviewAcceptDisclaimer: "راجع واقبل إخلاء المسؤولية للمتابعة",
    startBuildingSwms: "بدء بناء SWMS",
    createComprehensiveDocumentation: "إنشاء وثائق السلامة الشاملة",
    "nav.dashboard": "لوحة القيادة",
    "nav.swms-builder": "منشئ SWMS",
    "nav.my-swms": "SWMS الخاص بي",
    "nav.safety-library": "مكتبة السلامة",
    "nav.help": "المساعدة والدعم",
    "nav.settings": "الإعدادات",
    "btn.new-swms": "SWMS جديد",
    "btn.view-all": "عرض الكل",
    "btn.generate": "إنتاج",
    "swms.step1.title": "تفاصيل المشروع والمقاول",
    "swms.step1.desc": "معلومات المشروع وتفاصيل المقاول وتحديد العمل عالي المخاطر",
    "swms.step2.title": "أنشطة العمل وتقييم المخاطر",
    "swms.step2.desc": "تفصيل العمل التفصيلي وتقييمات المخاطر الشاملة",
    "swms.step3.title": "المصنع والمعدات والتدريب",
    "swms.step3.desc": "مواصفات المعدات ومتطلبات التدريب والتصاريح",
    "swms.step4.title": "الطوارئ والمراقبة",
    "swms.step4.desc": "إجراءات الطوارئ وعمليات المراجعة/المراقبة",
    "swms.step5.title": "إخلاء المسؤولية القانونية",
    "swms.step5.desc": "قبول الشروط وإخلاء المسؤولية",
    "swms.step6.title": "الوثيقة النهائية",
    "swms.step6.desc": "إنتاج وثيقة SWMS كاملة",
    "swms.back.dashboard": "العودة إلى لوحة القيادة",
    "swms.builder": "منشئ SWMS",
    "swms.create.comprehensive": "إنشاء وثائق السلامة الشاملة",
    "swms.save.close": "حفظ وإغلاق",
    "swms.step": "خطوة",
    "swms.of": "من",
    "swms.progress": "التقدم",
    "swms.complete": "مكتمل",
    "swms.title": "عنوان SWMS",
    "swms.trade.type": "نوع المهنة",
    "swms.select.trade": "اختر مهنتك",
    "swms.job.name": "اسم العمل",
    "swms.job.number": "رقم العمل",
    "swms.project.address": "عنوان المشروع",
    "swms.project.location": "موقع/وصف المشروع",
    // Dashboard translations
    "manageSafetyCompliance": "إدارة الامتثال للسلامة",
    "draftSwms": "مسودة SWMS",
    "saveCompleteLater": "حفظ واستكمال لاحقاً",
    "completedSwms": "SWMS مكتملة",
    "projectSpecificDocumentation": "وثائق خاصة بالمشروع",
    "createNewSwms": "إنشاء SWMS جديد",
    "quickStart": "بداية سريعة",
    "recentSwmsDocuments": "وثائق SWMS الحديثة",
    "viewAll": "عرض الكل",
    "quickActions": "إجراءات سريعة",
    "nav.ai-generator": "منشئ الذكاء الاصطناعي",
    "nav.team": "الفريق",
    "nav.analytics": "التحليلات",
    "nav.account": "الحساب"
  },
  pt: {
    legalDisclaimer: "Isenção de Responsabilidade Legal",
    reviewAcceptDisclaimer: "Revise e aceite a isenção de responsabilidade para continuar",
    startBuildingSwms: "Começar a Construir SWMS",
    createComprehensiveDocumentation: "Criar documentação de segurança abrangente",
    "nav.dashboard": "Painel",
    "nav.swms-builder": "Construtor SWMS",
    "nav.my-swms": "Meus SWMS",
    "nav.safety-library": "Biblioteca de Segurança",
    "nav.help": "Ajuda e Suporte",
    "nav.settings": "Configurações",
    "btn.new-swms": "Novo SWMS",
    "btn.view-all": "Ver Todos",
    "btn.generate": "Gerar",
    "swms.step1.title": "Detalhes do Projeto e Empreiteiro",
    "swms.step1.desc": "Informações do projeto, detalhes do empreiteiro e identificação de trabalho de alto risco",
    "swms.step2.title": "Atividades de Trabalho e Avaliação de Riscos",
    "swms.step2.desc": "Divisão detalhada do trabalho e avaliações abrangentes de riscos",
    "swms.step3.title": "Planta, Equipamentos e Treinamento",
    "swms.step3.desc": "Especificações de equipamentos, requisitos de treinamento e licenças",
    "swms.step4.title": "Emergência e Monitoramento",
    "swms.step4.desc": "Procedimentos de emergência e processos de revisão/monitoramento",
    "swms.step5.title": "Isenção de Responsabilidade Legal",
    "swms.step5.desc": "Aceitar termos e isenção de responsabilidade",
    "swms.step6.title": "Documento Final",
    "swms.step6.desc": "Gerar documento SWMS completo",
    "swms.back.dashboard": "Voltar ao Painel",
    "swms.builder": "Construtor SWMS",
    "swms.create.comprehensive": "Criar documentação de segurança abrangente",
    "swms.save.close": "Salvar e Fechar",
    "swms.step": "Passo",
    "swms.of": "de",
    "swms.progress": "Progresso",
    "swms.complete": "Completo",
    "swms.title": "Título SWMS",
    "swms.trade.type": "Tipo de Ofício",
    "swms.select.trade": "Selecione seu ofício",
    "swms.job.name": "Nome do Trabalho",
    "swms.job.number": "Número do Trabalho",
    "swms.project.address": "Endereço do Projeto",
    "swms.project.location": "Localização/Descrição do Projeto",
    // Dashboard translations
    "manageSafetyCompliance": "Gerenciar Conformidade de Segurança",
    "draftSwms": "Rascunho SWMS",
    "saveCompleteLater": "Salvar e Completar Depois",
    "completedSwms": "SWMS Concluídos",
    "projectSpecificDocumentation": "Documentação Específica do Projeto",
    "createNewSwms": "Criar Novo SWMS",
    "quickStart": "Início Rápido",
    "recentSwmsDocuments": "Documentos SWMS Recentes",
    "viewAll": "Ver Todos",
    "quickActions": "Ações Rápidas",
    "nav.ai-generator": "Gerador IA",
    "nav.team": "Equipe",
    "nav.analytics": "Análises",
    "nav.account": "Conta"
  },
  ru: {
    legalDisclaimer: "Правовой Отказ от Ответственности",
    reviewAcceptDisclaimer: "Ознакомьтесь и примите отказ от ответственности, чтобы продолжить",
    startBuildingSwms: "Начать Создание SWMS",
    createComprehensiveDocumentation: "Создать комплексную документацию по безопасности",
    "nav.dashboard": "Панель Управления",
    "nav.swms-builder": "Конструктор SWMS",
    "nav.my-swms": "Мои SWMS",
    "nav.safety-library": "Библиотека Безопасности",
    "nav.help": "Помощь и Поддержка",
    "nav.settings": "Настройки",
    "btn.new-swms": "Новый SWMS",
    "btn.view-all": "Показать Все",
    "btn.generate": "Сгенерировать",
    "swms.step1.title": "Детали Проекта и Подрядчика",
    "swms.step1.desc": "Информация о проекте, детали подрядчика и выявление высокорисковых работ",
    "swms.step2.title": "Рабочие Действия и Оценка Рисков",
    "swms.step2.desc": "Подробная разбивка работ и комплексная оценка рисков",
    "swms.step3.title": "Оборудование, Техника и Обучение",
    "swms.step3.desc": "Спецификации оборудования, требования к обучению и разрешения",
    "swms.step4.title": "Экстренные Ситуации и Мониторинг",
    "swms.step4.desc": "Процедуры экстренных ситуаций и процессы проверки/мониторинга",
    "swms.step5.title": "Правовой Отказ от Ответственности",
    "swms.step5.desc": "Принять условия и отказ от ответственности",
    "swms.step6.title": "Финальный Документ",
    "swms.step6.desc": "Сгенерировать полный документ SWMS",
    "swms.back.dashboard": "Назад к Панели Управления",
    "swms.builder": "Конструктор SWMS",
    "swms.create.comprehensive": "Создать комплексную документацию по безопасности",
    "swms.save.close": "Сохранить и Закрыть",
    "swms.step": "Шаг",
    "swms.of": "из",
    "swms.progress": "Прогресс",
    "swms.complete": "Завершено",
    "swms.title": "Заголовок SWMS",
    "swms.trade.type": "Тип Профессии",
    "swms.select.trade": "Выберите свою профессию",
    "swms.job.name": "Название Работы",
    "swms.job.number": "Номер Работы",
    "swms.project.address": "Адрес Проекта",
    "swms.project.location": "Местоположение/Описание Проекта",
    // Dashboard translations
    "manageSafetyCompliance": "Управление Соблюдением Безопасности",
    "draftSwms": "Черновик SWMS",
    "saveCompleteLater": "Сохранить и Завершить Позже",
    "completedSwms": "Завершенные SWMS",
    "projectSpecificDocumentation": "Проектная Документация",
    "createNewSwms": "Создать Новый SWMS",
    "quickStart": "Быстрый Старт",
    "recentSwmsDocuments": "Недавние Документы SWMS",
    "viewAll": "Показать Все",
    "quickActions": "Быстрые Действия",
    "nav.ai-generator": "ИИ Генератор",
    "nav.team": "Команда",
    "nav.analytics": "Аналитика",
    "nav.account": "Аккаунт"
  },
  it: {
    legalDisclaimer: "Esclusione di Responsabilità Legale",
    reviewAcceptDisclaimer: "Rivedi e accetta l'esclusione di responsabilità per continuare",
    startBuildingSwms: "Inizia a Costruire SWMS",
    createComprehensiveDocumentation: "Crea documentazione di sicurezza completa",
    "nav.dashboard": "Cruscotto",
    "nav.swms-builder": "Costruttore SWMS",
    "nav.my-swms": "I Miei SWMS",
    "nav.safety-library": "Biblioteca della Sicurezza",
    "nav.help": "Aiuto e Supporto",
    "nav.settings": "Impostazioni",
    "btn.new-swms": "Nuovo SWMS",
    "btn.view-all": "Visualizza Tutto",
    "btn.generate": "Genera",
    "swms.step1.title": "Dettagli Progetto e Appaltatore",
    "swms.step1.desc": "Informazioni del progetto, dettagli dell'appaltatore e identificazione lavori ad alto rischio",
    "swms.step2.title": "Attività Lavorative e Valutazione Rischi",
    "swms.step2.desc": "Suddivisione dettagliata del lavoro e valutazioni complete dei rischi",
    "swms.step3.title": "Impianti, Attrezzature e Formazione",
    "swms.step3.desc": "Specifiche attrezzature, requisiti di formazione e permessi",
    "swms.step4.title": "Emergenza e Monitoraggio",
    "swms.step4.desc": "Procedure di emergenza e processi di revisione/monitoraggio",
    "swms.step5.title": "Esclusione di Responsabilità Legale",
    "swms.step5.desc": "Accettare termini ed esclusione di responsabilità",
    "swms.step6.title": "Documento Finale",
    "swms.step6.desc": "Genera documento SWMS completo",
    "swms.back.dashboard": "Torna al Cruscotto",
    "swms.builder": "Costruttore SWMS",
    "swms.create.comprehensive": "Crea documentazione di sicurezza completa",
    "swms.save.close": "Salva e Chiudi",
    "swms.step": "Passo",
    "swms.of": "di",
    "swms.progress": "Progresso",
    "swms.complete": "Completo",
    "swms.title": "Titolo SWMS",
    "swms.trade.type": "Tipo di Mestiere",
    "swms.select.trade": "Seleziona il tuo mestiere",
    "swms.job.name": "Nome Lavoro",
    "swms.job.number": "Numero Lavoro",
    "swms.project.address": "Indirizzo Progetto",
    "swms.project.location": "Posizione/Descrizione Progetto",
    // Dashboard translations
    "manageSafetyCompliance": "Gestire Conformità Sicurezza",
    "draftSwms": "Bozza SWMS",
    "saveCompleteLater": "Salva e Completa Dopo",
    "completedSwms": "SWMS Completati",
    "projectSpecificDocumentation": "Documentazione Specifica Progetto",
    "createNewSwms": "Crea Nuovo SWMS",
    "quickStart": "Avvio Rapido",
    "recentSwmsDocuments": "Documenti SWMS Recenti",
    "viewAll": "Visualizza Tutto",
    "quickActions": "Azioni Rapide",
    "nav.ai-generator": "Generatore IA",
    "nav.team": "Team",
    "nav.analytics": "Analisi",
    "nav.account": "Account"
  },
  nl: {
    legalDisclaimer: "Juridische Disclaimer",
    reviewAcceptDisclaimer: "Bekijk en accepteer de disclaimer om door te gaan",
    startBuildingSwms: "Begin met SWMS Bouwen",
    createComprehensiveDocumentation: "Maak uitgebreide veiligheidsdocumentatie",
    "nav.dashboard": "Dashboard",
    "nav.swms-builder": "SWMS Builder",
    "nav.my-swms": "Mijn SWMS",
    "nav.safety-library": "Veiligheidsbibliotheek",
    "nav.help": "Hulp & Ondersteuning",
    "nav.settings": "Instellingen",
    "btn.new-swms": "Nieuwe SWMS",
    "btn.view-all": "Alles Bekijken",
    "btn.generate": "Genereren",
    "swms.step1.title": "Project & Aannemer Details",
    "swms.step1.desc": "Projectinformatie, aannemer details en hoog-risico werk identificatie",
    "swms.step2.title": "Werkactiviteiten & Risicobeoordeling",
    "swms.step2.desc": "Gedetailleerde werkonderverdeling en uitgebreide risicobeoordeling",
    "swms.step3.title": "Installatie, Apparatuur & Training",
    "swms.step3.desc": "Apparatuurspecificaties, trainingsvereisten en vergunningen",
    "swms.step4.title": "Noodgeval & Monitoring",
    "swms.step4.desc": "Noodprocedures en beoordeling/monitoring processen",
    "swms.step5.title": "Juridische Disclaimer",
    "swms.step5.desc": "Voorwaarden en aansprakelijkheid disclaimer accepteren",
    "swms.step6.title": "Einddocument",
    "swms.step6.desc": "Volledig SWMS document genereren",
    "swms.back.dashboard": "Terug naar Dashboard",
    "swms.builder": "SWMS Builder",
    "swms.create.comprehensive": "Maak uitgebreide veiligheidsdocumentatie",
    "swms.save.close": "Opslaan & Sluiten",
    "swms.step": "Stap",
    "swms.of": "van",
    "swms.progress": "Voortgang",
    "swms.complete": "Voltooid",
    "swms.title": "SWMS Titel",
    "swms.trade.type": "Vaktype",
    "swms.select.trade": "Selecteer uw vak",
    "swms.job.name": "Taaknaam",
    "swms.job.number": "Taaknummer",
    "swms.project.address": "Projectadres",
    "swms.project.location": "Projectlocatie/Beschrijving",
    // Dashboard translations
    "manageSafetyCompliance": "Veiligheidsnaleving Beheren",
    "draftSwms": "Concept SWMS",
    "saveCompleteLater": "Opslaan en Later Voltooien",
    "completedSwms": "Voltooide SWMS",
    "projectSpecificDocumentation": "Projectspecifieke Documentatie",
    "createNewSwms": "Nieuwe SWMS Maken",
    "quickStart": "Snelle Start",
    "recentSwmsDocuments": "Recente SWMS Documenten",
    "viewAll": "Alles Bekijken",
    "quickActions": "Snelle Acties",
    "nav.ai-generator": "AI Generator",
    "nav.team": "Team",
    "nav.analytics": "Analytics",
    "nav.account": "Account"
  },
  hi: {
    legalDisclaimer: "कानूनी अस्वीकरण",
    reviewAcceptDisclaimer: "जारी रखने के लिए अस्वीकरण की समीक्षा करें और स्वीकार करें",
    startBuildingSwms: "SWMS निर्माण शुरू करें",
    createComprehensiveDocumentation: "व्यापक सुरक्षा दस्तावेज़ीकरण बनाएं",
    "nav.dashboard": "डैशबोर्ड",
    "nav.swms-builder": "SWMS बिल्डर",
    "nav.my-swms": "मेरा SWMS",
    "nav.safety-library": "सुरक्षा पुस्तकालय",
    "nav.help": "सहायता और समर्थन",
    "nav.settings": "सेटिंग्स",
    "btn.new-swms": "नया SWMS",
    "btn.view-all": "सभी देखें",
    "btn.generate": "उत्पन्न करें",
    "swms.step1.title": "परियोजना और ठेकेदार विवरण",
    "swms.step1.desc": "परियोजना जानकारी, ठेकेदार विवरण और उच्च जोखिम कार्य पहचान",
    "swms.step2.title": "कार्य गतिविधियां और जोखिम आकलन",
    "swms.step2.desc": "विस्तृत कार्य विभाजन और व्यापक जोखिम आकलन",
    "swms.step3.title": "संयंत्र, उपकरण और प्रशिक्षण",
    "swms.step3.desc": "उपकरण विनिर्देश, प्रशिक्षण आवश्यकताएं और अनुमतियां",
    "swms.step4.title": "आपातकाल और निगरानी",
    "swms.step4.desc": "आपातकालीन प्रक्रियाएं और समीक्षा/निगरानी प्रक्रियाएं",
    "swms.step5.title": "कानूनी अस्वीकरण",
    "swms.step5.desc": "नियम और दायित्व अस्वीकरण स्वीकार करें",
    "swms.step6.title": "अंतिम दस्तावेज़",
    "swms.step6.desc": "पूर्ण SWMS दस्तावेज़ उत्पन्न करें",
    "swms.back.dashboard": "डैशबोर्ड पर वापस",
    "swms.builder": "SWMS बिल्डर",
    "swms.create.comprehensive": "व्यापक सुरक्षा दस्तावेज़ीकरण बनाएं",
    "swms.save.close": "सेव करें और बंद करें",
    "swms.step": "चरण",
    "swms.of": "का",
    "swms.progress": "प्रगति",
    "swms.complete": "पूर्ण",
    "swms.title": "SWMS शीर्षक",
    "swms.trade.type": "व्यापार प्रकार",
    "swms.select.trade": "अपना व्यापार चुनें",
    "swms.job.name": "कार्य नाम",
    "swms.job.number": "कार्य संख्या",
    "swms.project.address": "परियोजना पता",
    "swms.project.location": "परियोजना स्थान/विवरण",
    // Dashboard translations
    "manageSafetyCompliance": "सुरक्षा अनुपालन प्रबंधन",
    "draftSwms": "मसौदा SWMS",
    "saveCompleteLater": "सेव करें और बाद में पूरा करें",
    "completedSwms": "पूर्ण SWMS",
    "projectSpecificDocumentation": "परियोजना विशिष्ट प्रलेखन",
    "createNewSwms": "नया SWMS बनाएं",
    "quickStart": "त्वरित प्रारंभ",
    "recentSwmsDocuments": "हाल के SWMS दस्तावेज़",
    "viewAll": "सभी देखें",
    "quickActions": "त्वरित कार्य",
    "nav.ai-generator": "एआई जेनरेटर",
    "nav.team": "टीम",
    "nav.analytics": "विश्लेषणात्मक",
    "nav.account": "खाता"
  },
  vi: {
    legalDisclaimer: "Tuyên Bố Miễn Trách Nhiệm Pháp Lý",
    reviewAcceptDisclaimer: "Xem xét và chấp nhận tuyên bố miễn trách nhiệm để tiếp tục",
    startBuildingSwms: "Bắt Đầu Xây Dựng SWMS",
    createComprehensiveDocumentation: "Tạo tài liệu an toàn toàn diện",
    "nav.dashboard": "Bảng Điều Khiển",
    "nav.swms-builder": "Trình Xây Dựng SWMS",
    "nav.my-swms": "SWMS Của Tôi",
    "nav.safety-library": "Thư Viện An Toàn",
    "nav.help": "Trợ Giúp & Hỗ Trợ",
    "nav.settings": "Cài Đặt",
    "btn.new-swms": "SWMS Mới",
    "btn.view-all": "Xem Tất Cả",
    "btn.generate": "Tạo",
    "swms.step1.title": "Chi Tiết Dự Án và Nhà Thầu",
    "swms.step1.desc": "Thông tin dự án, chi tiết nhà thầu và xác định công việc có rủi ro cao",
    "swms.step2.title": "Hoạt Động Làm Việc và Đánh Giá Rủi Ro",
    "swms.step2.desc": "Phân tích công việc chi tiết và đánh giá rủi ro toàn diện",
    "swms.step3.title": "Nhà Máy, Thiết Bị và Đào Tạo",
    "swms.step3.desc": "Thông số kỹ thuật thiết bị, yêu cầu đào tạo và giấy phép",
    "swms.step4.title": "Khẩn Cấp và Giám Sát",
    "swms.step4.desc": "Quy trình khẩn cấp và quy trình xem xét/giám sát",
    "swms.step5.title": "Tuyên Bố Miễn Trách Nhiệm Pháp Lý",
    "swms.step5.desc": "Chấp nhận điều khoản và tuyên bố miễn trách nhiệm",
    "swms.step6.title": "Tài Liệu Cuối Cùng",
    "swms.step6.desc": "Tạo tài liệu SWMS hoàn chỉnh",
    "swms.back.dashboard": "Quay Lại Bảng Điều Khiển",
    "swms.builder": "Trình Xây Dựng SWMS",
    "swms.create.comprehensive": "Tạo tài liệu an toàn toàn diện",
    "swms.save.close": "Lưu & Đóng",
    "swms.step": "Bước",
    "swms.of": "của",
    "swms.progress": "Tiến Độ",
    "swms.complete": "Hoàn Thành",
    "swms.title": "Tiêu Đề SWMS",
    "swms.trade.type": "Loại Nghề",
    "swms.select.trade": "Chọn nghề của bạn",
    "swms.job.name": "Tên Công Việc",
    "swms.job.number": "Số Công Việc",
    "swms.project.address": "Địa Chỉ Dự Án",
    "swms.project.location": "Vị Trí/Mô Tả Dự Án",
    // Dashboard translations
    "manageSafetyCompliance": "Quản Lý Tuân Thủ An Toàn",
    "draftSwms": "Bản Nháp SWMS",
    "saveCompleteLater": "Lưu và Hoàn Thành Sau",
    "completedSwms": "SWMS Đã Hoàn Thành",
    "projectSpecificDocumentation": "Tài Liệu Cụ Thể Dự Án",
    "createNewSwms": "Tạo SWMS Mới",
    "quickStart": "Bắt Đầu Nhanh",
    "recentSwmsDocuments": "Tài Liệu SWMS Gần Đây",
    "viewAll": "Xem Tất Cả",
    "quickActions": "Hành Động Nhanh",
    "nav.ai-generator": "Trình Tạo AI",
    "nav.team": "Nhóm",
    "nav.analytics": "Phân Tích",
    "nav.account": "Tài Khoản"
  },
  th: {
    legalDisclaimer: "ข้อจำกัดความรับผิดชอบทางกฎหมาย",
    reviewAcceptDisclaimer: "ตรวจสอบและยอมรับข้อจำกัดความรับผิดชอบเพื่อดำเนินการต่อ",
    startBuildingSwms: "เริ่มสร้าง SWMS",
    createComprehensiveDocumentation: "สร้างเอกสารความปลอดภัยที่ครอบคลุม",
    "nav.dashboard": "แดชบอร์ด",
    "nav.swms-builder": "ตัวสร้าง SWMS",
    "nav.my-swms": "SWMS ของฉัน",
    "nav.safety-library": "ห้องสมุดความปลอดภัย",
    "nav.help": "ความช่วยเหลือและการสนับสนุน",
    "nav.settings": "การตั้งค่า",
    "btn.new-swms": "SWMS ใหม่",
    "btn.view-all": "ดูทั้งหมด",
    "btn.generate": "สร้าง",
    "swms.step1.title": "รายละเอียดโครงการและผู้รับเหมา",
    "swms.step1.desc": "ข้อมูลโครงการ รายละเอียดผู้รับเหมา และการระบุงานที่มีความเสี่ยงสูง",
    "swms.step2.title": "กิจกรรมการทำงานและการประเมินความเสี่ยง",
    "swms.step2.desc": "การแบ่งงานโดยละเอียดและการประเมินความเสี่ยงที่ครอบคลุม",
    "swms.step3.title": "โรงงาน อุปกรณ์ และการฝึกอบรม",
    "swms.step3.desc": "ข้อกำหนดอุปกรณ์ ความต้องการการฝึกอบรม และใบอนุญาต",
    "swms.step4.title": "เหตุฉุกเฉินและการตรวจสอบ",
    "swms.step4.desc": "ขั้นตอนฉุกเฉินและกระบวนการทบทวน/ตรวจสอบ",
    "swms.step5.title": "ข้อจำกัดความรับผิดชอบทางกฎหมาย",
    "swms.step5.desc": "ยอมรับข้อกำหนดและข้อจำกัดความรับผิดชอบ",
    "swms.step6.title": "เอกสารสุดท้าย",
    "swms.step6.desc": "สร้างเอกสาร SWMS ที่สมบูรณ์",
    "swms.back.dashboard": "กลับไปที่แดชบอร์ด",
    "swms.builder": "ตัวสร้าง SWMS",
    "swms.create.comprehensive": "สร้างเอกสารความปลอดภัยที่ครอบคลุม",
    "swms.save.close": "บันทึกและปิด",
    "swms.step": "ขั้นตอน",
    "swms.of": "จาก",
    "swms.progress": "ความคืบหน้า",
    "swms.complete": "เสร็จสิ้น",
    "swms.title": "ชื่อ SWMS",
    "swms.trade.type": "ประเภทอาชีพ",
    "swms.select.trade": "เลือกอาชีพของคุณ",
    "swms.job.name": "ชื่องาน",
    "swms.job.number": "หมายเลขงาน",
    "swms.project.address": "ที่อยู่โครงการ",
    "swms.project.location": "ตำแหน่ง/คำอธิบายโครงการ",
    // Dashboard translations
    "manageSafetyCompliance": "จัดการการปฏิบัติตามความปลอดภัย",
    "draftSwms": "ร่าง SWMS",
    "saveCompleteLater": "บันทึกและทำให้เสร็จในภายหลัง",
    "completedSwms": "SWMS ที่เสร็จสิ้น",
    "projectSpecificDocumentation": "เอกสารเฉพาะโครงการ",
    "createNewSwms": "สร้าง SWMS ใหม่",
    "quickStart": "เริ่มต้นอย่างรวดเร็ว",
    "recentSwmsDocuments": "เอกสาร SWMS ล่าสุด",
    "viewAll": "ดูทั้งหมด",
    "quickActions": "การดำเนินการที่รวดเร็ว",
    "nav.ai-generator": "เครื่องมือสร้าง AI",
    "nav.team": "ทีม",
    "nav.analytics": "การวิเคราะห์",
    "nav.account": "บัญชี"
  },
  tr: {
    legalDisclaimer: "Yasal Sorumluluk Reddi",
    reviewAcceptDisclaimer: "Devam etmek için sorumluluk reddini inceleyin ve kabul edin",
    startBuildingSwms: "SWMS Oluşturmaya Başla",
    createComprehensiveDocumentation: "Kapsamlı güvenlik belgeleri oluşturun",
    "nav.dashboard": "Kontrol Paneli",
    "nav.swms-builder": "SWMS Oluşturucu",
    "nav.my-swms": "SWMS'lerim",
    "nav.safety-library": "Güvenlik Kütüphanesi",
    "nav.help": "Yardım ve Destek",
    "nav.settings": "Ayarlar",
    "btn.new-swms": "Yeni SWMS",
    "btn.view-all": "Tümünü Görüntüle",
    "btn.generate": "Oluştur",
    "swms.step1.title": "Proje ve Müteahhit Detayları",
    "swms.step1.desc": "Proje bilgileri, müteahhit detayları ve yüksek riskli iş tanımlaması",
    "swms.step2.title": "İş Faaliyetleri ve Risk Değerlendirmesi",
    "swms.step2.desc": "Detaylı iş dağılımı ve kapsamlı risk değerlendirmeleri",
    "swms.step3.title": "Tesis, Ekipman ve Eğitim",
    "swms.step3.desc": "Ekipman özellikleri, eğitim gereksinimleri ve izinler",
    "swms.step4.title": "Acil Durum ve İzleme",
    "swms.step4.desc": "Acil durum prosedürleri ve inceleme/izleme süreçleri",
    "swms.step5.title": "Yasal Sorumluluk Reddi",
    "swms.step5.desc": "Şartları ve sorumluluk reddini kabul edin",
    "swms.step6.title": "Son Belge",
    "swms.step6.desc": "Tam SWMS belgesi oluşturun",
    "swms.back.dashboard": "Kontrol Paneline Dön",
    "swms.builder": "SWMS Oluşturucu",
    "swms.create.comprehensive": "Kapsamlı güvenlik belgeleri oluşturun",
    "swms.save.close": "Kaydet ve Kapat",
    "swms.step": "Adım",
    "swms.of": "of",
    "swms.progress": "İlerleme",
    "swms.complete": "Tamamlandı",
    "swms.title": "SWMS Başlığı",
    "swms.trade.type": "Meslek Türü",
    "swms.select.trade": "Mesleğinizi seçin",
    "swms.job.name": "İş Adı",
    "swms.job.number": "İş Numarası",
    "swms.project.address": "Proje Adresi",
    "swms.project.location": "Proje Konumu/Açıklaması",
    // Dashboard translations
    "manageSafetyCompliance": "Güvenlik Uyumluluğu Yönetimi",
    "draftSwms": "Taslak SWMS",
    "saveCompleteLater": "Kaydet ve Daha Sonra Tamamla",
    "completedSwms": "Tamamlanmış SWMS",
    "projectSpecificDocumentation": "Projeye Özel Dokümantasyon",
    "createNewSwms": "Yeni SWMS Oluştur",
    "quickStart": "Hızlı Başlangıç",
    "recentSwmsDocuments": "Son SWMS Belgeleri",
    "viewAll": "Tümünü Görüntüle",
    "quickActions": "Hızlı İşlemler",
    "nav.ai-generator": "AI Üretici",
    "nav.team": "Takım",
    "nav.analytics": "Analitik",
    "nav.account": "Hesap"
  }
};

const currentLanguage = (() => {
  if (typeof window !== "undefined") {
    return localStorage.getItem("selectedLanguage") || "en";
  }
  return "en";
})();

export function translate(key: string): string {
  const translations_typed = translations as Record<string, Record<string, string>>;
  const currentTranslations = translations_typed[currentLanguage];
  
  if (!currentTranslations) {
    console.warn(`No translations found for language: ${currentLanguage}, falling back to English`);
    return translations_typed["en"][key] || key;
  }
  
  const translation = currentTranslations[key];
  
  if (!translation) {
    console.warn(`Translation missing for key: ${key} in language: ${currentLanguage}, falling back to English`);
    return translations_typed["en"][key] || key;
  }
  
  return translation;
}

export function getCurrentLanguage(): string {
  return currentLanguage;
}

export function setLanguage(language: string) {
  if (typeof window !== "undefined") {
    localStorage.setItem("selectedLanguage", language);
    window.location.reload();
  }
}

export const supportedLanguages = [
  { code: "en", name: "English", flag: "🇺🇸" },
  { code: "zh", name: "中文", flag: "🇨🇳" },
  { code: "es", name: "Español", flag: "🇪🇸" },
  { code: "fr", name: "Français", flag: "🇫🇷" },
  { code: "de", name: "Deutsch", flag: "🇩🇪" },
  { code: "ja", name: "日本語", flag: "🇯🇵" },
  { code: "ko", name: "한국어", flag: "🇰🇷" },
  { code: "ar", name: "العربية", flag: "🇸🇦" },
  { code: "pt", name: "Português", flag: "🇵🇹" },
  { code: "ru", name: "Русский", flag: "🇷🇺" },
  { code: "it", name: "Italiano", flag: "🇮🇹" },
  { code: "nl", name: "Nederlands", flag: "🇳🇱" },
  { code: "hi", name: "हिन्दी", flag: "🇮🇳" },
  { code: "vi", name: "Tiếng Việt", flag: "🇻🇳" },
  { code: "th", name: "ไทย", flag: "🇹🇭" },
  { code: "tr", name: "Türkçe", flag: "🇹🇷" }
];

export const LANGUAGES = supportedLanguages;