import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { AlertTriangle, FileText, Shield, Users } from "lucide-react";

export default function LegalDisclaimer() {
  return (
    <div className="max-w-4xl mx-auto space-y-6 p-6">
      <div className="text-center mb-8">
        <AlertTriangle className="mx-auto h-12 w-12 text-amber-500 mb-4" />
        <h1 className="text-3xl font-bold mb-2">Legal Disclaimer</h1>
        <p className="text-gray-600">
          Important legal information regarding the use of Safety Sensei SWMS Builder
        </p>
      </div>

      <Card>
        <CardHeader>
          <CardTitle className="flex items-center">
            <FileText className="mr-2 h-5 w-5" />
            Document Accuracy and Responsibility
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <p className="text-sm text-gray-700">
            The Safe Work Method Statements (SWMS) generated by Safety Sensei are provided as a starting point and guidance tool only. 
            Users are solely responsible for:
          </p>
          <ul className="list-disc pl-6 space-y-2 text-sm text-gray-700">
            <li>Reviewing and verifying all generated content for accuracy and completeness</li>
            <li>Ensuring all risk assessments are appropriate for their specific work environment</li>
            <li>Adapting control measures to suit actual site conditions and equipment</li>
            <li>Compliance with all applicable local, state, and federal legislation</li>
            <li>Obtaining appropriate approvals and permits as required</li>
          </ul>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle className="flex items-center">
            <Shield className="mr-2 h-5 w-5" />
            Limitation of Liability
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <p className="text-sm text-gray-700">
            Safety Sensei Pty Ltd and its affiliates disclaim all liability for:
          </p>
          <ul className="list-disc pl-6 space-y-2 text-sm text-gray-700">
            <li>Any incidents, injuries, or damages resulting from the use of generated SWMS documents</li>
            <li>Inaccuracies or omissions in automatically generated content</li>
            <li>Non-compliance with legislation or industry standards</li>
            <li>Consequential, indirect, or special damages of any kind</li>
          </ul>
          <div className="bg-amber-50 border border-amber-200 rounded-lg p-4 mt-4">
            <p className="text-sm text-amber-800 font-medium">
              ⚠️ Important: Users must ensure all SWMS documents are reviewed by qualified safety professionals 
              before implementation on any worksite.
            </p>
          </div>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle className="flex items-center">
            <Users className="mr-2 h-5 w-5" />
            Professional Advice
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <p className="text-sm text-gray-700">
            Safety Sensei does not provide professional safety consulting services. All generated content should be:
          </p>
          <ul className="list-disc pl-6 space-y-2 text-sm text-gray-700">
            <li>Reviewed by qualified Workplace Health and Safety professionals</li>
            <li>Validated against current Australian Standards and legislation</li>
            <li>Customized for specific site conditions and hazards</li>
            <li>Approved by appropriate site management before implementation</li>
          </ul>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>Compliance and Updates</CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <p className="text-sm text-gray-700">
            While Safety Sensei endeavors to maintain current information:
          </p>
          <ul className="list-disc pl-6 space-y-2 text-sm text-gray-700">
            <li>Legislation and standards may change without notice</li>
            <li>Users are responsible for ensuring compliance with current requirements</li>
            <li>Regular updates to SWMS documents may be necessary</li>
            <li>AI-generated content may contain errors or omissions</li>
          </ul>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>Acceptance of Terms</CardTitle>
        </CardHeader>
        <CardContent>
          <p className="text-sm text-gray-700">
            By using Safety Sensei SWMS Builder, you acknowledge that you have read, understood, and agree to be bound by this disclaimer. 
            You accept full responsibility for the use of generated documents and agree to hold Safety Sensei harmless from any claims 
            arising from their use.
          </p>
          <div className="bg-primary/50 border border-primary/200 rounded-lg p-4 mt-4">
            <p className="text-sm text-primary/800">
              For questions about this disclaimer or our services, please contact our support team at support@safetysensei.com.au
            </p>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}